                echo "-----------------------------------------------------------------------"
                echo "Si llegaste hasta aquí, ¡enhorabuena!"
                echo " "
                echo "GADGET es una colección de funciones y macros, rescatadas desde"
                echo "Internet como hechas por mí, puestas de forma armoniosa en un"
                echo "conjunto de herramientas al servicio del programador de C, tanto"
                echo "novato como experto, pero más bien novato, porque un experto no"
                echo "necesitará esta mierda."
                echo " " 
                echo "Importante!"
                echo "     Para ejecutar un programa, puedes hacerlo de tres formas:"
                echo " "
                echo "  1) ./ccpre.sh <nombre-programa>   (sin extensión)"
                echo " "
                echo "        compilará el programa, y enlaza la librería compartida."
                echo "        Una vez compilado, podrás ejecutarlo, pero no sabrás si"
                echo "        tu programa tiene leacks de memoria."
                echo " "
                echo "  2) ./ccpre.sh <programa> . -c"
                echo " "
                echo "        compila, enlaza, y ejecuta el programa con VALGRIND (-c)."
                echo "        VALGRIND deberás tenerlo instalado."
                echo " "
                echo "  3) ./ccpre.sh <programa> -static [-c]"
                echo " "
                echo "        compila, y enlaza la librería estática."
                echo " "
                echo "        Una vez que hayas probado tu programa de este modo, podrás"
                echo "        ejecutarlo sin problemas:"
                echo "          ./programa"
                echo " "
                echo " Dudas, aportes y reclamaciones de créditos: "
                echo " "
                echo "        daniel.stuardo@gmail.com"
                echo " "
                echo " Pregunta por Mr. Dalien."
                echo "-----------------------------------------------------------------------"

